### ISSUE TITLE
Can't edit a reopened issue

### ISSUE THREAD

**Issue by mwenge** [esprehn/chromium-codereview#96] opened 2014-08-29 09:28 UTC
If you close an issue and reopen it, you can't edit the issue description anymore.

**Comment by esprehn** [comment] 2014-08-29 21:35
I can't reproduce this, do you have an example?

**Comment by esprehn** [comment] 2014-09-02 19:33
Closing this, please comment if this still reproduces.

**Closed as completed by esprehn** 2014-09-02 19:33 UTC
Labels: bug, needs repro
