### ISSUE TITLE
CC list can overflow into the diff

### ISSUE THREAD

**Issue by dglazkov** [esprehn/chromium-codereview#5] opened 2014-06-07 02:34 UTC
See https://codereview.chromium.org/app/#/issue/183273010 for an example.

**Comment by esprehn** [comment] 2014-06-07 05:31
I don't see that, what version of Chrome are you in? Can you post a screenshot? Those are flex boxes, it shouldn't have any overflow at all.

**Comment by dglazkov** [comment] 2014-06-07 15:18
35.0.1916.116 (Official Build 270289)
![Screenshot](http://i.imgur.com/8lszlsE.png)

**Comment by esprehn** [comment] 2014-06-08 02:14
Can you try M36? I'm not really supporting M35.

**Comment by esprehn** [comment] 2014-06-11 23:19
I can't reproduce this, it smells like a rendering engine bug. Closing the issue, reopen if you still see it in 36+.

**Closed as completed by esprehn** 2014-06-11 23:19 UTC
Labels: bug, needs repro
