### ISSUE TITLE
Comments should show by default even if they're hidden by the fold

### ISSUE THREAD

**Issue by zetafunction** [esprehn/chromium-codereview#95] opened 2014-08-28 17:17 UTC
An example is in https://codereview.chromium.org/514123002, patchset 1.

**Comment by zetafunction** [comment] 2014-08-28 17:19
Actually, I notice the server is returning errors when I try to expand the context for cc/output/delegating_renderer.cc so that might have something to do with it. I'll try again later and see what happens.

**Comment by esprehn** [comment] 2014-08-29 02:57
This is a duplicate of bug #84 

The server error you see is a Rietveld bug. Hopefully I'll get real APIs in Rietveld soon so I don't need to screen scrape that stuff.

**Closed as completed by esprehn** 2014-08-29 02:57 UTC
Labels: bug, duplicate
